// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozoncp/ocp-role-api/internal/repo (interfaces: Repo)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/ozoncp/ocp-role-api/internal/model"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddRoles mocks base method.
func (m *MockRepo) AddRoles(arg0 []*model.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoles", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRoles indicates an expected call of AddRoles.
func (mr *MockRepoMockRecorder) AddRoles(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoles", reflect.TypeOf((*MockRepo)(nil).AddRoles), arg0)
}

// ListRoles mocks base method.
func (m *MockRepo) ListRoles(arg0, arg1 uint) ([]*model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", arg0, arg1)
	ret0, _ := ret[0].([]*model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockRepoMockRecorder) ListRoles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockRepo)(nil).ListRoles), arg0, arg1)
}

// RemoveRole mocks base method.
func (m *MockRepo) RemoveRole(arg0 *model.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRole", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRole indicates an expected call of RemoveRole.
func (mr *MockRepoMockRecorder) RemoveRole(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRole", reflect.TypeOf((*MockRepo)(nil).RemoveRole), arg0)
}
